### PR TITLE
Fix NYTParser for new article format

### PR DESCRIPTION
**Pull request by carlgieringer**
1. Use BeautifulSoup4 in NYTParser
2. Look for different tags in NYTParser to support new article format

### CODE REVIEW

**Comment by iamvishnurajan** [comment]
I was able to resolve my error and updated the parser to include a few additional items; a pull request is added here now. Thank you much for helping to get this going - it is much appreciated.

**Comment by iamvishnurajan** [comment]
FYI - it seems like NYT has updated the article content/formats once again. At least the scraper that worked last week no longer seems to work. Seems like this will need a more robust and generic solution that can deal with whatever it is NYT is doing behind the scenes.

**Comment by snagacarl** [comment]
Hi Vishnu, I just pushed a change that should fix that issue.

**Comment by carlgieringer** [comment]
I see you caught some things I missed, like the footer and including h2's in the p_tags.  I'll merge your PR and include it in this one.

**Comment by iamvishnurajan** [comment]
Thank you so much for taking care of this Carl! This works great for me on all articles I've tried now as well.

**Comment by ecprice** [comment]
Looks pretty great!  One last issue -- it's not good at recording corrections.

For example, in
https://www.nytimes.com/2018/06/05/world/europe/greece-macedonia.html

the correction at the end is captured, but without the "Correction: June 5, 2018" part.

[A separate issue is whether NewsDiffs should really be storing all this structured data as a flat text file, but that's for another day.]

A related issue appears in
http://www.nytimes.com/2013/04/05/movies/roger-ebert-film-critic-dies.html

where the corrections are missing, and instead there's the "A version of this article appears..." text that shouldn't be captured.

**Comment by carlgieringer** [comment]
Hi Eric, I pushed a fix to including the correction.  Unfortunately the actual date appears to be loaded dynamically, so it will just say: `Correction: Because of an editing error, an earlier version...`

**Comment by ecprice** [comment]
I'm still not seeing the correction for the ebert example I linked, and the "Order Reprints| Today's Paper|Subscribe" at the bottom of the article shouldn't be there.

**Comment by snagacarl** [comment]
Hi Eric, the Ebert example you linked is an old article, right?  I thought we weren't fixing old articles.  You said that issuing fixes for old articles would cause the scraper to see changes that weren't actually changes, and I think you implied this might overload the system.

**Comment by snagacarl** [comment]
Which article are you referring to when you say `the "Order Reprints| Today's Paper|Subscribe" at the bottom of the article shouldn't be there.`?

**Comment by ecprice** [comment]
I'm saying that this version of the parser changes how old articles are parsed, including that ebert article.

The "Order Reprints" etc:  I see this on every article I've checked, including
https://www.nytimes.com/2018/06/05/world/europe/greece-macedonia.html

For
https://www.nytimes.com/2018/06/11/world/asia/trump-kim-summitmeeting.html

the bottom reads:

```Choe Sang-Hun contributed reporting from Seoul, South Korea. A version of this article appears in print on , on Page A1 of the New York edition with the headline: Taunts Put Aside As Trump and Kim Meet to End Crisis. Order Reprints | Today’s Paper | Subscribe```

Is there anyway to fix the missing date there?

**Comment by carlgieringer** [comment]
Oh the greece article you linked has it.  And the current code doesn't capture that correction, even without the date.

**Comment by carlgieringer** [comment]
Okay, I fixed capturing the correction for the Greece article.  Hoooopefully this addresses all the issues except for the dynamic dates.

I have a branch in my fork that supports getting the dynamic date.  I'm not sure we want to introduce this into the main branch now for the reasons mentioned above.

https://github.com/carlgieringer/newsdiffs/tree/feature/dynamic-html

**Comment by iamvishnurajan** [comment]
Hi - it looks like the bottom of article fix is close, but I found two recent cases where it errors out:
https://www.nytimes.com/2018/06/02/us/politics/trump-ramadan-dinner.html
https://www.nytimes.com/2018/05/30/us/politics/ivanka-trump-china-trademarks.html

It looks like in those two articles, the "bottom of article" tag exists, but there is no content (other than the social media share buttons). The lack of any text there seems to generate an error condition.

**Comment by carlgieringer** [comment]
Thank you, @iamvishnurajan !  I had a dream that something was wrong with that line...and then I forgot to check it.  Thank you for finding the error!  It should be fixed now.

**Comment by ecprice** [comment]
Thanks everybody!  I've updated the code in production; let's hope it works.

**Pull request merged**
